#!/usr/bin/env python3
"""Sync one ancestor's data from an ANC repo checkout into a game-ready JS module.

Reads data/people/{id}.json and data/journeys/{id}.json from an ANC checkout and
emits src/data/{slug}.js: a plain JS object the game imports directly (no fetch,
no build step, works from file:// or any static server).

Usage:
    python3 tools/sync_ancestor.py --anc /path/to/ANC --id I182197770339 --slug josiah
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def build_waypoint(w: dict) -> dict:
    return {
        "seq": w["seq"],
        "place": w["place"]["raw"],
        "lat": w["place"].get("lat"),
        "lng": w["place"].get("lng"),
        "date": w["date"]["raw"] if w.get("date") else None,
        "year": w["date"]["year"] if w.get("date") else None,
        "event": w["event"],
        "narrative": w.get("narrative"),
        "confidence": w["confidence"],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--anc", required=True, help="path to an ANC repo checkout")
    ap.add_argument("--id", required=True, help="GEDCOM id, e.g. I182197770339")
    ap.add_argument("--slug", required=True, help="output slug, e.g. josiah")
    args = ap.parse_args()

    anc = Path(args.anc)
    person = json.loads((anc / "data" / "people" / f"{args.id}.json").read_text())
    journey = json.loads((anc / "data" / "journeys" / f"{args.id}.json").read_text())

    # Prefer the reviewed journey's own birth/death waypoints over the raw machine
    # vitals: the journey carries corrections (e.g. a birth year the research
    # disproved), and the game should tell the corrected story, not the export.
    waypoints = journey["waypoints"]
    birth_wp = next((w for w in waypoints if w["event"] == "birth"), None)
    death_wp = next((w for w in waypoints if w["event"] == "death"), None)
    vitals = person.get("vitals", {})
    birth_year = (birth_wp or {}).get("date", {}).get("year") if birth_wp else (
        vitals.get("birth") or {}).get("date", {}).get("year")
    death_year = (death_wp or {}).get("date", {}).get("year") if death_wp else (
        vitals.get("death") or {}).get("date", {}).get("year")

    out = {
        "id": args.id,
        "name": person["name"]["full"],
        "birthYear": birth_year,
        "deathYear": death_year,
        "summary": journey.get("summary"),
        "journeyStatus": journey.get("status"),
        "waypoints": [build_waypoint(w) for w in journey["waypoints"]],
    }

    out_dir = Path(__file__).resolve().parent.parent / "src" / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{args.slug}.js"
    js = (
        f"// Generated by tools/sync_ancestor.py from ANC data/people/{args.id}.json\n"
        f"// and data/journeys/{args.id}.json. Do not hand-edit — re-run the sync script\n"
        f"// after the source records change.\n"
        f"export const {args.slug.upper()} = {json.dumps(out, indent=2, ensure_ascii=False)};\n"
    )
    out_path.write_text(js, encoding="utf-8")
    print(f"wrote {out_path} ({len(out['waypoints'])} waypoints)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
